New external command for scenareos where LBs are attached externally not explicitly via feed
sky-uk/feed pull request #238
Opened 2021-09-23 08:06 UTC by chbatey

The motivation for this is to run feed in GKE.

Firstly we were going to follow a similar model to the NLBs are attach to pre-existing NLBs but in the end it was simpler to allow the GKE ingress controller to create and attach internal/external LBs to the feed pods and feed update each ingress to point to a static host.

So looks like this:

![image](https://user-images.githubusercontent.com/1866779/134473528-e98b728a-6389-45ce-8fea-bc7f7ea8c3dd.png)

2021-09-23 08:22 UTC, howardburgess approved these changes
Elegant solution 👍🏻

2021-09-23 09:14 UTC, jsravn requested changes
I think this can be even more generic than "external" since it will work with any setup that has static domains for feed. So I suggest we rename it to "static" and update the README as well.

2021-09-23 09:15 UTC, jsravn commented on feed-ingress/cmd/external.go
> +
remove whitespace

2021-09-24 09:52 UTC, chbatey commented
Will re-name to static and update readme 👍

2021-09-24 13:56 UTC, jsravn approved these changes

2021-09-29 07:51 UTC, merged